baseURL      = 'https://example.org/'
title        = 'Tailwind CSS CLI Simple'
disableKinds = ['taxonomy', 'term', "sitemap"]

[outputs]
    home = ["html"]

[build]
    [build.buildStats]
        enable     = true
        disableIDs = true
    [[build.cachebusters]]
        source = "assets/notwatching/hugo_stats\\.json"
        target = "css"
    [[build.cachebusters]]
        source = "(postcss|tailwind)\\.config\\.js"
        target = "css"

[module]
    [module.hugoVersion]
        min = "0.128.0"
    [[module.mounts]]
        source = "assets"
        target = "assets"
    [[module.mounts]]
        source = "content"
        target = "content"
    [[module.mounts]]
        source = "layouts"
        target = "layouts"
    [[module.mounts]]
        source = "layouts"
        target = "assets/layouts"
    [[module.mounts]]
        source       = "hugo_stats.json"
        target       = "assets/notwatching/hugo_stats.json"
        disableWatch = true

[markup]
    [markup.highlight]
        style = 'modus-vivendi'
